# Generated by Django 5.0.1 on 2024-02-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compID', models.CharField(max_length=100, unique=True)),
                ('parameter1', models.CharField(blank=True, max_length=100)),
                ('parameter2', models.CharField(blank=True, max_length=100)),
                ('parameter3', models.CharField(blank=True, max_length=100)),
                ('parameter4', models.CharField(blank=True, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
