# Generated by Django 5.0.1 on 2024-12-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0002_parameter_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='parameter1',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='parameter2',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='parameter3',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='parameter4',
        ),
        migrations.AddField(
            model_name='parameter',
            name='currency_pair',
            field=models.CharField(blank=True, default='USD/EUR', max_length=100),
        ),
        migrations.AddField(
            model_name='parameter',
            name='notional',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='parameter',
            name='product',
            field=models.CharField(choices=[('FOR', 'FX Cash'), ('OPT', 'FX Options'), ('BASEMETALS', 'Basemetals'), ('ENERGY', 'Energy'), ('AGS', 'Agriculture'), ('INDEX', 'Indices')], default='FOR', max_length=100),
        ),
        migrations.AddField(
            model_name='parameter',
            name='security',
            field=models.CharField(blank=True, default='FXFORWARD', max_length=100),
        ),
        migrations.AddField(
            model_name='parameter',
            name='side',
            field=models.CharField(choices=[('1', 'Buy'), ('2', 'Sell')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='parameter',
            name='value_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
